# Generated by Django 5.1.7 on 2025-03-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='crerate_at',
            new_name='created_at',
        ),
    ]
